### ISSUE TITLE
Send text on data channel is not working

### ISSUE THREAD

**Issue by nhancv** [oney/react-native-webrtc-server#10]
I've tried to send text message but it does't work correctly. Please check.

**Comment by smolleyes** [comment]
hi

First, thanks for your hard work ! great :)

same problem for me ok on the heroku app but not with this git 

trying to fix this, seems that pcPeers just have local client id in the array, no others clients

thanks

**Comment by smolleyes** [comment]
hummm

hummm time to understand the code it seems that dataChannel.onmessage do not work...

pressText ok -> get id then pc.textDataChannel.send(msg) is not "catched" by onmessage, searching why

**Comment by nhancv** [comment]
Hi Smolleyes, 
I had fixed that bug in my version at https://github.com/nhancv/nc-rcn-webrtc-server
I follow at https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample and realized current code create data channel separately, but right flow it must be connected together.
